name: Test Action

on: push

jobs:
  test:
   name: Test Action
   runs-on: ubuntu-latest
   
   steps:
    - name: Checkout action
      uses: actions/checkout@v2
       
    - name: Parse value as boolean
      uses: ./
      id: value_as_flag
      with:
        value: true
        default: false

    - name: Fail if not true
      if: steps.value_as_flag.outputs.value != 'true'
      uses: actions/github-script@v2
      with:
        script: |
          console.log("This step should not run");
          core.setFailed('Condition was not matched as expected');
