name: Test Secrets as Flags

on: push

jobs:
  test:
   name: Test Action
   runs-on: ubuntu-latest
   
   steps:
    - name: Checkout action
      uses: actions/checkout@v2
       
    - name: Parse secret FLAG_SECRET_TRUE
      uses: ./
      id: value_as_flag_true
      with:
        value: ${{ secrets.FLAG_SECRET_TRUE }}
        default: false

    - name: Parse secret FLAG_SECRET_FALSE
      uses: ./
      id: value_as_flag_false
      with:
        value: ${{ secrets.FLAG_SECRET_FALSE }}
        default: true
     
    - name: Parse non-existant secret
      uses: ./
      id: value_as_flag_missing
      with:
        value: ${{ secrets.FLAG_SECRET_MISSING }}
        default: false

    - name: Check Values
      uses: actions/github-script@v2
      env:
        FLAG_TRUE: ${{ steps.value_as_flag_true.outputs.value }}
        FLAG_FALSE: ${{ steps.value_as_flag_false.outputs.value }}
        FLAG_MISSING: ${{ steps.value_as_flag_missing.outputs.value }}
      with:
        script: |
          console.log(`Flag TRUE:    ${process.env.FLAG_TRUE === 'true' ? 'correct' : 'incorrect'}`);
          console.log(`Flag FALSE:   ${process.env.FLAG_FALSE === 'false' ? 'correct' : 'incorrect'}`);
          console.log(`Flag MISSING: ${process.env.FLAG_MISSING === 'false' ? 'correct' : 'incorrect'}`);

    - name: Fail errors in parsing
      if: |
        (steps.value_as_flag_true.outputs.value != 'true') 
        || (steps.value_as_flag_false.outputs.value != 'false') 
        || (steps.value_as_flag_missing.outputs.value != 'false')
      uses: actions/github-script@v2
      with:
        script: |
          console.log("The secret values have not been parsed correctly");
          core.setFailed('Secret values have not been parsed correctly');
